#!/usr/bin/env bash

echo "EpiDoc"
java -jar validation/jing.jar validation/tei-epidoc.rng $@

# For the DHARMA schemas, we must first figure out (from the files themselves?)
# which schema we should use.
